MyProfessionFriend/MyProfessionFriend/Controllers/ActivityController.cs
using BussinessLayer.Concrete;
using BussinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyProfessionFriend.Controllers
{
    public class ActivityController : Controller
    {
        ActivityManager am = new ActivityManager(new EfActivityDal());
        // GET: Activity
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetActivityList()
        {
            var activityvalues = am.GetList();
            return View(activityvalues);
        }
        [HttpGet]
        public ActionResult AddActivity()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddActivity(Activity p)
        {
            //am.ActivityAddBL(p);
            ActivityValidator activityValidator = new ActivityValidator();
            ValidationResult results = activityValidator.Validate(p);
            if(results.IsValid)
            {
                am.ActivityAdd(p);
                return RedirectToAction("GetActivityList");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MyProfessionFriend/MyProfessionFriend/Views/Activity/AddActivity.cshtml
@model EntityLayer.Concrete.Activity

@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>Yeni Etkinlik Ekleme Sayfası</h1>
<br />
@using(Html.BeginForm("AddActivity", "Activity", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.Label("Etkinlik Adı")
                    @Html.TextBoxFor(x=>x.ActivityName)
                    @Html.ValidationMessageFor(x=>x.ActivityName)
                    <br /><br />
                    @Html.Label("Açıklamayı yazınız")
                    @Html.TextBoxFor(x=>x.ActivityContent)
                    @Html.ValidationMessageFor(x=>x.ActivityContent)
                    <br /><br />
                    <button>Kaydet</button>
                </div>
            }



@*<form class="form-group" method="post">
    <input type="text" placeholder="Etkinlik Adı" name="ActivityName" class="form-control" />
    <br />
    <input type="text" placeholder="Açıklama Giriniz" name="ActivityName" class="form-control" />
    <br />
    <button class="btn btn-primary">Ekle</button>
</form>*@

MyProfessionFriend/MyProfessionFriend/Views/Activity/GetActivityList.cshtml
@using EntityLayer.Concrete
@model List<Activity>


@{
    ViewBag.Title = "AllMedia";
    Layout = "~/Views/Shared/_NewsfeedLayout.cshtml";
}

<h1><p>ACTIVITIES</p></h1>

@foreach (var item in Model)
{
<div class="post-content">
    <h5><p>@item.ActivityName</p></h5>
    

    <div class="post-container">

        <div class="post-text">
            <p>@item.ActivityContent <i class="em em-anguished"></i> <i class="em em-anguished"></i> <i class="em em-anguished"></i></p>
        </div>

        <img src="@item.People.PeopleImage" alt="user" class="profile-photo-md pull-left" />
        <div class="post-detail">
            <div class="user-info">
                <h5><a href="timeline.html" class="profile-link">@item.People.PeopleName</a> <span class="following">following</span></h5>
                <p class="text-muted">Published a activity about @item.ActivityDate</p>
            </div>
            <div class="reaction">
                <a href="/Activity/JoinActivity" class="btn btn-info">Join</a>
                <a class="btn text-green"><i class="icon ion-thumbsup"></i> 13</a>
                <a class="btn text-red"><i class="fa fa-thumbs-down"></i> 0</a>
            </div>
            <div class="line-divider"></div>



            <div class="line-divider"></div>
           
        </div>
    </div>
    </div>
    }

    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <br />
        <table>
            <tr>
                <th>ID</th>
                <th>Ad</th>
                <th>Açıklama</th>
                <th>Tarih</th>
                <th>Durum</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ActivityID</td>
                    <td>@item.ActivityName</td>
                    <td>@item.ActivityContent</td>
                    <td>@item.ActivityDate</td>
                    <td>@item.ActivityStatus</td>
                </tr>
            }
        </table>*@
    <br />
    <a href="/Activity/AddActivity" class="btn btn-info">Yeni Etkinlik</a>

MyProfessionFriend/MyProfessionFriend/Views/Activity/Index.cshtml
@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h3>Etkinlikler</h3>
<br />
<table class="table table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Adı</th>
        <th>Tarih</th>
        <th>Durum</th>
    </tr>
    <tr>
        <td>3</td>
        <td>dfs</td>
        <td>fsdf</td>
        <td>sdfsd</td>
    </tr>
    <tr>
        <td>5</td>
        <td>dfs</td>
        <td>fsdf</td>
        <td>sdfsd</td>
    </tr>
    <tr>
        <td>6</td>
        <td>dfs</td>
        <td>fsdf</td>
        <td>sdfsd</td>
    </tr>
</table>
<button class="=btn btn-info">Yeni Etkinlik</button>
<button class="btn btn-warning">Etkinlik Listesi</button>