MyProfessionFriend/MyProfessionFriend/Controllers/SchoolPartController.cs
using BussinessLayer.Concrete;
using BussinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MyProfessionFriend.Controllers
{
    public class SchoolPartController : Controller
    {
        // GET: SchoolPart
        SchoolPartManager spm = new SchoolPartManager(new EfSchoolPartDal());
        SchoolManager sm = new SchoolManager(new EfSchoolDal());

        public ActionResult Index()
        {
            var scpartvalues = spm.GetList();
            return View(scpartvalues);
        }

        [HttpGet]
        public ActionResult AddSchoolPart()
        {
            List<SelectListItem> valueschool = (from x in sm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.SchoolName,
                                                    Value = x.SchoolID.ToString()
                                                }).ToList();
            
            ViewBag.vls = valueschool;
            return View();
        }

        [HttpPost]
        public ActionResult AddSchoolPart(SchoolPart p)
        {

            spm.SchoolPartAdd(p);
            return RedirectToAction("Index");
        }

        
        public ActionResult SchoolPartBySchool(int id)
        {
            var schoolpartvalues = spm.GetListBySchoolID(id);
            return View(schoolpartvalues);
        }

        [HttpGet]
        public ActionResult EditSchoolPart(int id)
        {
            List<SelectListItem> valueschool = (from x in sm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.SchoolName,
                                                    Value = x.SchoolID.ToString()
                                                }).ToList();

            ViewBag.vls = valueschool;
            var SchoolPartValue = spm.GetByID(id);
            return View(SchoolPartValue);
        }

        [HttpPost]
        public ActionResult EditSchoolPart(SchoolPart p)
        {
            spm.SchoolPartUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteSchoolPart(int id)
        {
            var SchoolPartValue = spm.GetByID(id);
            SchoolPartValue.ScpartStatus=false;
            spm.SchoolPartDelete(SchoolPartValue);
            return RedirectToAction("Index");
        }
    }
}

MyProfessionFriend/MyProfessionFriend/Views/SchoolPart/AddSchoolPart.cshtml
@model EntityLayer.Concrete.SchoolPart
@{
    ViewBag.Title = "AddSchoolPart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Bölüm Ekle</h2>
<br />
@using (Html.BeginForm("AddSchoolPart", "SchoolPart", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Bölüm Adı")
        @Html.TextBoxFor(x => x.ScpartName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ScpartName)
        <br /><br />
        @Html.Label("Okul Adı")
        @Html.DropDownListFor(x=>x.SchoolID, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
        <br /><br />
        <button class="btn btn-primary">Kaydet</button>
    </div>
}

MyProfessionFriend/MyProfessionFriend/Views/SchoolPart/EditSchoolPart.cshtml
@model EntityLayer.Concrete.SchoolPart

@{
    ViewBag.Title = "EditSchoolPart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Bölüm Düzenle</h2>
@using(Html.BeginForm("EditSchoolPart", "SchoolPart", FormMethod.Post))
            {
<div class="form-group">
    @Html.Label("Bölüm ID")
    @Html.TextBoxFor(x => x.ScpartID, new { @class = "form-control" })
    <br />
    @Html.Label("Bölüm Adı")
    @Html.TextBoxFor(x => x.ScpartName, new { @class = "form-control" })
    <br />
    @Html.Label("Okul")
    @Html.DropDownListFor(x => x.SchoolID, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
            }

MyProfessionFriend/MyProfessionFriend/Views/SchoolPart/Index.cshtml
@using EntityLayer.Concrete
@model List<SchoolPart>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{  string color = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Bölüm İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Bölüm Adı
                            </th>
                            <th style="width: 30%">
                                Okul Adı
                            </th>
                            <th style="width: 30%">
                                Durum
                            </th>
                            <th style="width: 20%">
                                Üye Sayısı
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            //if(item.School.SchoolName == " a okulu")
                            //{
                            //    color = "badge badge-warning";
                            //}
                            //if(item.School.SchoolName == " b okulu")
                            //{
                            //    color = "badge badge-success";
                            //}
                            <tr>
                                <td>
                                    @item.ScpartID
                                </td>
                                <td>
                                    <a>
                                        @item.ScpartName
                                    </a>
                                    <br />
                                    <small>
                                        Üyeler
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/Admin/dist/img/avatar.png">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    @item.ScpartStatus
                                </td>
                                <td class="project-state">
                                    <span class="badge badge-success">@item.School.SchoolName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/People/PeopleBySchoolPart/@item.ScpartID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Üyeler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/SchoolPart/EditSchoolPart/@item.ScpartID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/SchoolPart/DeleteSchoolPart/@item.ScpartID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

<a href="SchoolPart/AddSchoolPart/" class="btn btn-primary"> Yeni Bölüm Girişi</a>

@*<h2>Yeni Bölüm Ekle</h2>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Bölüm Adı</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ScpartID</td>
                <td>@item.ScpartName</td>
            </tr>
        }
    </table>
    <br />
    <a href="/SchoolPart/AddSchoolPart" class="btn btn-info">Yeni Bölüm Ekle</a>*@

MyProfessionFriend/MyProfessionFriend/Views/SchoolPart/PeopleBySchoolPart.cshtml
@{
    ViewBag.Title = "PeopleBySchoolPart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            <div class="time-label">
                                <span class="bg-success">Tarih</span>
                            </div>
                            <!-- /.timeline-label -->
                            <!-- timeline item -->
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">Test</a> Deneme</h3>
                                    <div class="timeline-body">
                                        İçerik
                                    </div>
                                </div>
                            </div>
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MyProfessionFriend/MyProfessionFriend/Views/SchoolPart/SchoolPartBySchool.cshtml
@using EntityLayer.Concrete
@model List<SchoolPart>

@{
    ViewBag.Title = "SchoolPartBySchool";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@item.ScpartName</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Peoples</a> Deneme</h3>
                                        <div class="timeline-body">
                                            İçerik
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>